### ISSUE TITLE
Is the full robocrystallographer dataset available?

### ISSUE THREAD

**Issue by sgbaird** [hackingmaterials/robocrystallographer#121]
The paper discusses how robocrystallographer was applied to ~110k materials from the Materials Project. Naturally, it's also integrated directly into Materials Project. Are the JSON files and/or feature vectors available for this large dataset? I can run this mysel too, but figured if the data can be shared, I would ask. The feature vector list would be preferred. I'd also be fine to grab it via an API, but it didn't seem like that was an option.

Alternatively, perhaps `robocrys mp-856` shortcuts the actual computation and pulls the JSON data directly from https://materialsproject.org?

**Comment by utf** [comment]
Hi @sgbaird - Unfortunately, the full dataset isn't available. We are working on exposing some of the data via the Materials Project API but this doesn't include the full json dump, just the text descriptions.

**Comment by sgbaird** [comment]
@utf Thanks for letting me know! Does that have mostly to do with copyright? Curious for later when I get the full dataset processed

**Comment by hasan-sayeed** [comment]
@utf Will the text description data be available anytime soon?

**Comment by sgbaird** [comment]
If anyone is interested, you can download specified properties for all stable (`e_above_hull < 0.5`) Materials Project entries and split these into train/val/test (after replacing <your-mp-key> and downloading any dependencies you don't already have) using the following:

```python
# see https://workshop.materialsproject.org/lessons/04_materials_api/api_use/
from pymatgen.ext.matproj import MPRester
import pandas as pd
import pickle

#list of properties to extract
props=['cif','task_id','pretty_formula','unit_cell_formula','energy','energy_per_atom','volume','density','nsites','elements','nelements','formation_energy_per_atom','e_above_hull']
subprops = props[1:] #ignore 'cif'

#download the energies and materials project IDs for compounds with e_above_hull less than 0.5
with MPRester("<your-mp-key>") as m:
    results = m.query({"e_above_hull": {"$lt": 0.5}}, properties=props,chunk_size=2000)

#separate mpids, stable CIFs, and other properties
mpids = [d["task_id"] for d in results]
stableCIFs = [d["cif"] for d in results]
data = [[d[prop] for d in results] for prop in subprops] #ignore 'cif'

#save the data to various formats
with open('stableCIFs.pkl', 'wb') as f:
    pickle.dump(stableCIFs, f)

df = pd.DataFrame(mpids,columns=['mp-ids'])
df.to_csv('stable_mp-ids_formulas.csv',index=False)

df2 = pd.DataFrame(data,index=subprops).transpose()
df2.to_csv('stable_props.csv')
```

Then, in order to run robocrystallographer on `stableCIFs.pkl` via a SLURM cluster using the [submitit](https://github.com/facebookincubator/submitit) package (after replacing <my-partition> and <my-account>):
```python
import submitit
import pickle
import pandas as pd
import pymatgen.core as mg
from robocrys.featurize.featurizer import RobocrysFeaturizer

#functions
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    out = []
    for i in range(0, len(lst), n):
        #yield lst[i:i + n]
        out.append(lst[i:i + n])
    return out

def robofeaturize( cifstr_list ) :
    """featurize a list of CIF strings using robycrys and assign ['failed'] for CIFs that produce an error"""
    featurizer = RobocrysFeaturizer( {"use_conventional_cell": False, "symprec": 0.1} )
    nids = len(cifstr_list)
    features = [None]*nids
    for i in range(nids):
        cifstr = cifstr_list[i]
        structure = mg.Structure.from_str( cifstr, fmt="cif" )
        try:
            features[i] = featurizer.featurize( structure )
        except:
            print('failed ID: '+str(i))
            features[i] = ['failed']
    return features

#load stable CIFs
with open('stableCIFs.pkl', 'rb') as f:
    stableCIFs = pickle.load(f)

#SLURM/submitit commands
##setup
log_folder = "log_test/%j"
walltime = 240 #300
chunksize = 260 #360
pars = chunks(stableCIFs, chunksize) #split CIFs into chunks
partition, account = ['<my-partition>','<my-account>']

##execution
executor = submitit.AutoExecutor(folder=log_folder)
executor.update_parameters(timeout_min=walltime, slurm_partition=partition, slurm_additional_parameters={'account': account})

jobs = executor.map_array(robofeaturize, pars)  # sbatch array

#concatenation
njobs = len(jobs)
output = []
for i in range(njobs):
    output.append(jobs[i].result())

#save features
with open('stable_features.pkl', 'wb') as f:
    pickle.dump(output, f)

#combine MP properties and robocrys features
lbls = RobocrysFeaturizer().feature_labels()
df2 = pd.read_csv('stable_props.csv')
df = pd.DataFrame([i if isinstance(i,list) else [i] for j in output for i in j], columns=lbls) #stack output from multiple jobs
df3 = pd.concat([df2,df],axis=1) #combine robocrys and MP props
df3 = df3.drop(df3[df3[lbls[0]] == 'failed'].index) # remove failed rows, lbls[0] is mineral_prototype as of 2021-05-27

#save combined dataframe
#df = pd.DataFrame( output, columns=lbls )
df3.to_csv('stable_features.csv')
```

**Comment by sgbaird** [comment]
https://figshare.com/articles/dataset/materials_project_and_robocrystallographer_features_for_stable_compounds/14692263

**Comment by mkhorton** [comment]
Hi @sgbaird, @hasan-sayeed,

We build robocrystallographer data for as many materials as we can, and expose this [via the API](https://api.materialsproject.org/docs#/Robocrystallographer/search_robocrys__get).

Specifically, the data we expose is defined by this document model: https://github.com/materialsproject/emmet/blob/d77b80d51669edcbbfb8de2180db087afacfc321/emmet-core/emmet/core/robocrys.py#L24-L51

The text/description is already there, and _some_ of the condensed structure is available too.

If you there's more information in the condensed structure you want to be available via the API, but currently is not, all we'd have to do is add those additional fields from the document model, and then the API would be able to pull them from our database.

I'll add this to our TODOs but I'm not sure when we'll have chance to do this, but if it's urgent we'd be happy to accept a PR too.

**Comment by mkhorton** [comment]
I'll note that this information via the API is updated automatically with future database releases too (e.g., as we add new materials, or incorporate bug fixes), so it will always be current.

**Comment by sgbaird** [comment]
@mkhorton thanks for this! I think we've moved away somewhat from using the machine learning features of robocrystallographer towards using structural fingerprints like CrystalNN.

Aside: @hasan-sayeed did a study that used the robocrystallographer text descriptions in an NLP sense which was interesting. From what I remember it improved performance over a baseline model.

**Comment by mkhorton** [comment]
I realized after posting that this issue was almost a year old 😅

Glad you've figured out a different solution!
