### ISSUE TITLE
rare grammar issue

### ISSUE THREAD

**Issue by computron** [hackingmaterials/robocrystallographer#13]
"There is three shorter"

(py37) computron-7:~ ajain$ robocrys mp-1143

Al2O3 is Corundum structured and crystallizes in the trigonal R-3c space group. The structure is three-dimensional. Al(1)3+ is bonded to six equivalent O(1)2- atoms to form a mixture of edge, face, and corner-sharing AlO6 octahedra. The corner-sharing octahedra tilt angles range from 48–60°. There is three shorter (1.87 Å) and three longer (1.99 Å) Al(1)–O(1) bond length. O(1)2- is bonded to four equivalent Al(1)3+ atoms to form a mixture of distorted edge and corner-sharing OAl4 trigonal pyramids.

**Comment by utf** [comment]
Fixed.
