### ISSUE TITLE
"Molecules" should be "atoms" or "ions" if len(molecule)==1

### ISSUE THREAD

**Issue by mkhorton** [hackingmaterials/robocrystallographer#23]
e.g. see https://materialsproject.org/materials/mp-1111410/

> The structure is three-dimensional and consists of eight sodium molecules and one TiHgF6 framework.

Also, perhaps if only a single framework "and one" could become "inside a" instead?

**Comment by utf** [comment]
Thanks @mkhorton. This should be an easy fix.

**Comment by utf** [comment]
I implemented both these suggestions. The description now reads:

>>> (Na)₂TiHgF₆ crystallizes in the cubic Fm̅3m space group. The structure is three-dimensional and consists of two sodium atoms inside a TiHgF6 framework.

Thanks for the suggestion!

**Comment by mkhorton** [comment]
Excellent, looks great! Looks like the second TiHgF6 framework doesn't have the subscript but maybe that's just a copy and paste error?

**Comment by utf** [comment]
Good catch. I fixed that bug too.
