### ISSUE TITLE
can not run with latest pymatgen

### ISSUE THREAD

**Issue by antonmilev** [hackingmaterials/robocrystallographer#403]
robocrys MyStructure.cif 

returns this error:

Traceback (most recent call last):
  File "D:\pymatgen\robocrys.py", line 2, in <module>
    from robocrys import StructureCondenser, StructureDescriber
  File "D:\pymatgen\robocrys.py", line 2, in <module>
    from robocrys import StructureCondenser, StructureDescriber
ImportError: cannot import name 'StructureCondenser' from partially initialized module 'robocrys' (most likely due to a circular import) (D:\pymatgen\robocrys.py)

I installed this with

pip install robocrys

The same reproduces with:
>>> from robocrys import StructureCondenser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Geology\pymatgen\robocrys.py", line 2, in <module>
    from robocrys import StructureCondenser, StructureDescriber
ImportError: cannot import name 'StructureCondenser' from partially initialized module 'robocrys' (most likely due to a circular import) (D:\Geology\pymatgen\robocrys.py)

**Comment by utf** [comment]
Thanks for raising this. It has been fixed in the most recent version.
