### ISSUE TITLE
ValueError: Unexpected atomic number Z=119

### ISSUE THREAD

**Issue by zakidotai** [hackingmaterials/robocrystallographer#434]
Hi,
When I run the following command,
`from robocrys import StructureCondenser, StructureDescriber
`
I am getting the following error
`  File "/home/m3rg2000/miniconda3/envs/my_pymatgen/lib/python3.12/site-packages/pymatgen/core/periodic_table.py", line 526, in from_Z
    raise ValueError(f"Unexpected atomic number {Z=}")
ValueError: Unexpected atomic number Z=119`

I am using the following versions:
python==3.12.1
pymatgen==2024.2.8
robocrys==0.2.8

**Comment by JaGeo** [comment]
It is related to an issue with matminer : https://github.com/hackingmaterials/matminer/issues/924
Please downgrade to pymatgen version 2023.12.18.

**Comment by zakidotai** [comment]
> It is related to an issue with matminer : [hackingmaterials/matminer#924](https://github.com/hackingmaterials/matminer/issues/924) Please downgrade to pymatgen version 2023.12.18.

Thank you so much. I downgraded pymatgen's version to **2023.3.23** (as 
 mentioned in https://github.com/hackingmaterials/robocrystallographer/issues/433'
