### ISSUE TITLE
logging output progress

### ISSUE THREAD

**Issue by computron** [hackingmaterials/robocrystallographer#5]
The only log message I see when running robocrystallographer is "Adding oxidation states"

When running a structure that takes a long time, e.g.:
https://www.materialsproject.org/materials/mp-744259/

It is unclear whether the long time is due to the oxidation states, or some other structure analysis step since the log doesn't tell me when it's moving on to the next step.

I would suggest either no logs, or comprehensive logs

**Comment by utf** [comment]
I might remove the log file for now.

The vast majority of the time is spent on the mineral matching (about 70%+). So it will be interesting to see if the ABCNN matching can do better.

**Comment by computron** [comment]
yes I meant more for the console log than any file log

It adds noise to my console "Adding oxidation states" instead of just printing out the description

**Comment by utf** [comment]
I have removed logging.
